// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Totten.Solution.Ragstore.Infra.Data.Contexts.RagnaStoreContexts;

#nullable disable

namespace Totten.Solution.Ragstore.Infra.Data.Migrations.RagnaStore
{
    [DbContext(typeof(RagnaStoreContext))]
    [Migration("20250507074618_UserTableAndCallbackChanges")]
    partial class UserTableAndCallbackChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Totten.Solution.Ragstore.Domain.Features.AgentAggregation.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ServerId")
                        .HasColumnType("integer");

                    b.Property<int?>("ServerId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("ServerId1");

                    b.ToTable("Agents", (string)null);
                });

            modelBuilder.Entity("Totten.Solution.Ragstore.Domain.Features.CallbackAggregation.Callback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CallbackOwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<double>("ItemPrice")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ServerId")
                        .HasColumnType("integer");

                    b.Property<int?>("ServerId1")
                        .HasColumnType("integer");

                    b.Property<int>("StoreType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("ServerId1");

                    b.HasIndex("UserId");

                    b.ToTable("Callbacks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CallbackOwnerId = new Guid("d7aeb595-44a5-4f5d-822e-980f35ace12d"),
                            CreatedAt = new DateTime(2025, 5, 7, 7, 46, 18, 114, DateTimeKind.Utc).AddTicks(1528),
                            ItemId = 490037,
                            ItemPrice = 500000000.0,
                            Name = "CallbackObscuro",
                            ServerId = 1,
                            StoreType = 2,
                            UpdatedAt = new DateTime(2025, 5, 7, 7, 46, 18, 114, DateTimeKind.Utc).AddTicks(1532)
                        });
                });

            modelBuilder.Entity("Totten.Solution.Ragstore.Domain.Features.CallbackAggregation.CallbackSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SendIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Sended")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CallbacksSchedule", (string)null);
                });

            modelBuilder.Entity("Totten.Solution.Ragstore.Domain.Features.Servers.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Servers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 7, 7, 46, 18, 113, DateTimeKind.Utc).AddTicks(8907),
                            IsActive = false,
                            Name = "broTHOR",
                            SiteUrl = "https://playragnarokonlinebr.com",
                            UpdatedAt = new DateTime(2025, 5, 7, 7, 46, 18, 113, DateTimeKind.Utc).AddTicks(8909)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 5, 7, 7, 46, 18, 113, DateTimeKind.Utc).AddTicks(8913),
                            IsActive = false,
                            Name = "broVALHALLA",
                            SiteUrl = "https://playragnarokonlinebr.com",
                            UpdatedAt = new DateTime(2025, 5, 7, 7, 46, 18, 113, DateTimeKind.Utc).AddTicks(8913)
                        });
                });

            modelBuilder.Entity("Totten.Solution.Ragstore.Domain.Features.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ReceivePriceAlerts")
                        .HasColumnType("boolean");

                    b.Property<long>("SearchCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Totten.Solution.Ragstore.Domain.Features.AgentAggregation.Agent", b =>
                {
                    b.HasOne("Totten.Solution.Ragstore.Domain.Features.Servers.Server", null)
                        .WithMany("Agents")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Totten.Solution.Ragstore.Domain.Features.Servers.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId1");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Totten.Solution.Ragstore.Domain.Features.CallbackAggregation.Callback", b =>
                {
                    b.HasOne("Totten.Solution.Ragstore.Domain.Features.Servers.Server", null)
                        .WithMany("Callbacks")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Totten.Solution.Ragstore.Domain.Features.Servers.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId1");

                    b.HasOne("Totten.Solution.Ragstore.Domain.Features.Users.User", null)
                        .WithMany("Callbacks")
                        .HasForeignKey("UserId");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Totten.Solution.Ragstore.Domain.Features.Servers.Server", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Callbacks");
                });

            modelBuilder.Entity("Totten.Solution.Ragstore.Domain.Features.Users.User", b =>
                {
                    b.Navigation("Callbacks");
                });
#pragma warning restore 612, 618
        }
    }
}
